#!/bin/bash
# mod_battery_compile.sh — third-party mod battery, compile gate.
# Compiles every cloned third-party mod with the project's own amxxpc
# (AMX Mod X 1.8.3-dev from amxmodx-FWGS) against the project include set,
# augmented with each mod's own include files. Verdict per mod:
#   OK       — every listed sma compiled
#   PARTIAL  — some compiled (failures listed)
#   NOBUILD  — requires natives/modules we do not ship (e.g. ReAPI) — the
#              missing include names are reported; that is a FACT about the
#              mod's requirements, not an AMXX core failure.
set -u
ROOT=$(cd "$(dirname "$0")/.." && pwd)
AMXXPC=${AMXXPC:-$( [ -x /tmp/amxxpc-build/amxxpc ] && echo /tmp/amxxpc-build/amxxpc || echo "$ROOT/glue/out/amxxpc-host/amxxpc" )}
# absolute path is mandatory: the compiler runs with cwd switched to the
# per-mod output dir, so a relative AMXXPC would break there
case "$AMXXPC" in /*) ;; *) AMXXPC="$PWD/${AMXXPC#./}";; esac
[ -x "$AMXXPC" ] || { echo "amxxpc missing" >&2; exit 1; }
INC_STOCK=$(ls "$ROOT"/out/cs-host-test/cstrike/addons/amxmodx/scripting/include/*.inc 2>/dev/null | head -1 | xargs dirname)
[ -n "${INC_STOCK:-}" ] || { echo "stock includes missing — run run_cstrike_host_test.sh once" >&2; exit 1; }
WORK=/tmp/battery
rm -rf "$WORK"; mkdir -p "$WORK"
PASS_TOTAL=0; FAIL_TOTAL=0

compile_mod() {
	local name="$1"; shift
	local incdirs="$1"; shift   # colon-separated include dirs (recursive)
	local incdir="$WORK/$name-include"
	mkdir -p "$incdir"
	cp "$INC_STOCK"/*.inc "$incdir/" 2>/dev/null
	# mod's own includes win over stock; last dir wins on name clashes
	local d
	IFS=':' read -ra dirs <<< "$incdirs"
	for d in "${dirs[@]}"; do
		[ -d "$d" ] && ( cd "$d" && find . -name "*.inc" -exec cp {} "$incdir/" \; ) 2>/dev/null
	done
	# reapi_version.inc is build-generated upstream -- provide a compile stub
	if [ -f "$incdir/reapi.inc" ] && [ ! -f "$incdir/reapi_version.inc" ]; then
		cat > "$incdir/reapi_version.inc" <<'STUB'
// generated by mod_battery_compile.sh (upstream generates this at build time)
#if !defined REAPI_VERSION_MAJOR
	#define REAPI_VERSION_MAJOR 5
#endif
#if !defined REAPI_VERSION_MINOR
	#define REAPI_VERSION_MINOR 24
#endif
#define REAPI_VERSION %d05024
STUB
	fi
	# ColorChat wrapper onto the stock CromChat (which provides client_print_color)
	if [ ! -f "$incdir/ColorChat.inc" ] && [ -f "$incdir/cromchat.inc" ]; then
		printf '#if !defined client_print_color\n#include <cromchat>\n#endif\n' > "$incdir/ColorChat.inc"
	fi
	# compiler needs amxxpc32.so in cwd
	local out="$WORK/$name"
	mkdir -p "$out"
	cp /tmp/amxxpc-build/amxxpc32.so "$out/" 2>/dev/null
	local ok=0 fail=0 missing=""
	for sma in "$@"; do
		[ -d "$sma" ] && continue
		:
	done
	for sma in "$@"; do
		[ -f "$sma" ] || continue
		local base=$(basename "$sma")
		local log
		log=$(cd "$out" && "$AMXXPC" "$sma" -i"$incdir" -o"${base%.sma}.amxx" 2>&1)
		if echo "$log" | grep -q "Done\."; then
			ok=$((ok+1))
		else
			fail=$((fail+1))
			local miss
			miss=$(echo "$log" | grep -oE "Cannot read from file: \"[^\"]+\"|Error: cannot read from file: \"[^\"]+\"" | head -1)
			echo "    FAIL $base: $(echo "$log" | grep -m1 -E "Error|error")"
			[ -n "$miss" ] && missing="$missing $miss"
		fi
	done
	echo "[$name] compiled=$ok failed=$fail ${missing:+missing-includes:$missing}"
	PASS_TOTAL=$((PASS_TOTAL+ok)); FAIL_TOTAL=$((FAIL_TOTAL+fail))
}

M=/tmp/mods
# 1) BaseBuilder TURBO (the mod family played on bb_ maps)
compile_mod BaseBuilder-TURBO "$M/BaseBuilder-TURBO/cstrike/addons/amxmodx/scripting/include" \
	$(find "$M/BaseBuilder-TURBO/cstrike/addons/amxmodx/scripting" -maxdepth 1 -name "*.sma")
# 2) ReDeathmatch (CSDM family)
compile_mod ReDeathmatch "$M/ReDeathmatch_AMXX/cstrike/addons/amxmodx/scripting/include:/tmp/reapi/reapi/extra/amxmodx/scripting/include" \
	$(find "$M/ReDeathmatch_AMXX/cstrike/addons/amxmodx/scripting" -maxdepth 1 -name "*.sma")
# 3) ZP 5.0 — Rise of the Dead fork (vanilla AMXX 1.8.3+)
compile_mod ZP5-RiseOfTheDead "$M/Zombie-Plague-Rise-of-the-Dead/amxmodx/scripting/include" \
	$(find "$M/Zombie-Plague-Rise-of-the-Dead" -name "*.sma" | grep -vE "Новая папка")
# 4) ZP5 (mostten port)
compile_mod ZP5-mostten "$M/ZombiePlague-for-CS1.6/addons/amxmodx/scripting/include" \
	$(find "$M/ZombiePlague-for-CS1.6/addons/amxmodx/scripting" -maxdepth 1 -name "*.sma" | head -30)
# 5) Biohazard
compile_mod Biohazard "$M/biohazard-amxx/scripting/include" \
	$(find "$M/biohazard-amxx/scripting" -maxdepth 1 -name "*.sma" | head -12)
# 6) Deathrun (aLbaneso)
compile_mod Deathrun "$M/Deathrun/scripting/include" \
	$(find "$M/Deathrun/scripting" -maxdepth 1 -name "*.sma" | head -15)
# 7) ReGG (GunGame)
compile_mod ReGG "$M/regg/cstrike/addons/amxmodx/scripting/include:/tmp/reapi/reapi/extra/amxmodx/scripting/include:/tmp/mods/regg/cstrike/addons/amxmodx/scripting" \
	$(find "$M/regg/cstrike/addons/amxmodx/scripting" -maxdepth 1 -name "*.sma" | head -12)

echo "=================================="
echo "BATTERY COMPILE TOTAL: ok=$PASS_TOTAL failed=$FAIL_TOTAL"
